### ISSUE TITLE
x-kernel plugin not fully compatible with dracut version from focal

### ISSUE THREAD

**Issue by jocado** [kubiko/snapcraft-kernel-plugin#21]
Hi,

Not sure if this is really a valid issue or not, but thought it worth flagging just in case.

If not building using multipass [ as you can't when cross compiling I believe ], I generally do it in a system using an Ubuntu version that matches the base used in the snap, so I would build core20 snaps using focal, etc.

I was building a kernel kernel snap for core20 base using the x-kernel plugin [ thank you for it by the way ! ]. and found that it fails building the initrd with the following error:

```
++ ls /build/parts/kernel/build/ubuntu-core-initramfs/usr/lib/ubuntu-core-initramfs/uc-overlay
+ return 0
+ /build/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs create-initrd --root /build/parts/kernel/build/ubuntu-core-initramfs --kernelver=5.15.32-ucm-imx8m-plus-moo-snappy-dirty --kerneldir /build/parts/kernel/install/lib/modules/5.15.32-ucm-imx8m-plus-moo-snappy-dirty --firmwaredir /build/stage/firmware --skeleton /build/parts/kernel/build/ubuntu-core-initramfs/usr/lib/ubuntu-core-initramfs --output /build/parts/kernel/install/initrd.img
/usr/lib/dracut/dracut-install: invalid option -- 'r'
Usage: dracut-install -D DESTROOTDIR [OPTION]... -a SOURCE...
or: dracut-install -D DESTROOTDIR [OPTION]... SOURCE DEST
or: dracut-install -D DESTROOTDIR [OPTION]... -m KERNELMODULE [KERNELMODULE …]

Install SOURCE to DEST in DESTROOTDIR with all needed dependencies.

  KERNELMODULE can have the format:
     <absolute path> with a leading /
     =<kernel subdir>[/<kernel subdir>…] like '=drivers/hid'
     <module name>

  -D --destrootdir  Install all files to DESTROOTDIR as the root
  -a --all          Install all SOURCE arguments to DESTROOTDIR
  -o --optional     If SOURCE does not exist, do not fail
  -d --dir          SOURCE is a directory
  -l --ldd          Also install shebang executables and libraries
  -L --logdir <DIR> Log files, which were installed from the host to <DIR>
  -R --resolvelazy  Only install shebang executables and libraries
                     for all SOURCE files
  -H --hostonly     Mark all SOURCE files as hostonly

  -f --fips         Also install all '.SOURCE.hmac' files

  --module,-m       Install kernel modules, instead of files
  --kerneldir       Specify the kernel module directory
  --firmwaredirs    Specify the firmware directory search path with : separation
  --silent          Don't display error messages for kernel module install
  --modalias        Only generate module list from /sys/devices modalias list
  -o --optional     If kernel module does not exist, do not fail
  -p --mod-filter-path      Filter kernel modules by path regexp
  -P --mod-filter-nopath    Exclude kernel modules by path regexp
  -s --mod-filter-symbol    Filter kernel modules by symbol regexp
  -S --mod-filter-nosymbol  Exclude kernel modules by symbol regexp
  -N --mod-filter-noname    Exclude kernel modules by name regexp

  -v --verbose      Show more output
     --debug        Show debug output
     --version      Show package version
  -h --help         Show this help

Traceback (most recent call last):
  File "/build/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 248, in <module>
    main()
  File "/build/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 244, in main
    globals()[args.subcmd.replace("-", "_")](parser, args)
  File "/build/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 49, in create_initrd
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib/dracut/dracut-install', '-D', '/tmp/tmpwivq7cx4.ubuntu-core-initramfs/main', '-r', '/tmp/tmpwivq7cx4.ubuntu-core-initramfs/kernel', '--kerneldir', '/tmp/tmpwivq7cx4.ubuntu-core-initramfs/kernel/usr/lib/modules/5.15.32-ucm-imx8m-plus-ocado-snappy-dirty', '--firmwaredirs', '/tmp/tmpwivq7cx4.ubuntu-core-initramfs/kernel/usr/lib/firmware', '--module', '--optional', 'virtio_scsi']' returned non-zero exit status 1.
Failed to build 'kernel'.

Recommended resolution:
Check the build logs and ensure the part's configuration and sources are correct.
```

It seems that ` -r, --sysroot ` option for `dracut-install` is not support in the version of dracut available in focal.  If I manually add the version from jammy it works fine.

**dracut versions**
- focal:  `048+80-2`
- jammy: `051-1`

Like I say, not sure if you consider this an issue or not, but worth pointing out at least, in case this was not considered previously.

Cheers,
Just

**Comment by kubiko** [comment]
Hi @jocado
Thank you for the comment. This is a known issue, for the build to work correctly you need to add `snappy-dev/image` ppa definition to your `snapcraft.yaml`, see at the end. The latest version of the plugin will flag this for you and print you help on what to do. I pushed this change today.

ppa dependency was introduced when I moved from using intermediate  prebuilt `uc-initrd` snap, which I needed to also maintain and would often fall behind, to using directly `ubuntu-core-initramfs` tool. This is part of an effort to upstream the plugin.
those PRs are now open, feel free to comment on them, since once they land, if, then you can stop adding custom plugin to every kernel tree :)
`build-base: core20`: https://github.com/snapcore/snapcraft/pull/3922
`build-base: core22`: https://github.com/canonical/craft-parts/pull/287

Ultimately it became too cumbersome to keep the custom plugin up to date across numerous kernel trees (git submodules do not help as they lock to a particular commit).
This became an even bigger problem with the `core22` base.  snapcraft currently does not support custom plugins for `core22` base. You can lie and run build on jammy, while setting `build-base: core20` so you get the correct compiler and other toolchains, but you would be still using initrd base from focal. Plus seems wrong to build kernel snap for UC22 with `build-base: core20`. Sure it works but hey :)

As for use of the plugin. I personally do not use multipass at all. I run all my build in lxd containers or if my host matches the target series I might run it directly there.
I do maintain my own wrapper for container management. It sets up container for cross build and runs build in the project directory. Plus it runs build as ubuntu user mapped to your user, rather than root, so whole build is lot more usable.
You can see my wrapper here: https://github.com/kubiko/toolbox/blob/20/glue/bin/snapcraft-lxd-wrapper
source it and then you can run: `$ lxd_snapcraft`
if you source [snapcraft bash-completion](https://github.com/kubiko/toolbox/blob/20/glue/usr/share/bash-completion/completions/snapcraft), you also get better bash completion for cross-building and part management, like `lxd_snapcraft clean ` offers you a list of parts....

ppa definition to add to your `snapcraft.yaml`
```
package-repositories:
  - type: apt
    ppa: snappy-dev/image
```

cheers
Ondra

**Comment by jocado** [comment]
Makes complete sense.  Thanks for the detailed response :+1: 

I really hope you are able to upstream the plugin, as it seems a bit strange to me that there is no upstream kernel plugin for core20 or core22.  I assume it's partly because the main kernel snaps are built from ubuntu packages, and is not pressing for core maintenance.

In the meantime, thanks again for your current kernel plugin maintenance outside of snapcraft.


Cheers,
Just
